# Generated by Django 4.1.4 on 2023-08-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
    ]
